/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.nnov.nntc.mbuldov.java.mysql.app;

import java.util.*;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javenue.csv.Csv;
import ru.nnov.nntc.mbuldov.java.mysql.appdb.Lecturer;
import ru.nnov.nntc.mbuldov.java.mysql.appdb.Student;

/**
 *
 * @author student
 */
public class MasterForm extends javax.swing.JFrame {

    private final EntityManagerFactory emf = Persistence.createEntityManagerFactory("myJavaAppPU");
    public EntityManager em;
    
    // Диалоги, вызываемые из главной формы
    private final AboutJDialog aboutDlg = new AboutJDialog(this, rootPaneCheckingEnabled);
    private final SettingsJDialog settDialog = new SettingsJDialog(this, rootPaneCheckingEnabled);
    
    //Дополнительные формы, вызываемые из главной формы
    private final StudentsForm studForm = new StudentsForm(this);
    private final LecturersForm lectForm = new LecturersForm(this);
    
    // Подключение к базе данных
    public static Connection conn = null;
    
    /**
     * Creates new form MasterForm
     */
    
    public MasterForm() {
        initComponents();
        setLocationRelativeTo(null); // позиционировать форму по центу экрана
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        mainMenu = new javax.swing.JMenu();
        openStudFormMenuitem = new javax.swing.JMenuItem();
        openLectFormMenuitem = new javax.swing.JMenuItem();
        settingsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainMenu.setMnemonic('f');
        mainMenu.setText("Меню");

        openStudFormMenuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        openStudFormMenuitem.setText("Студенты");
        openStudFormMenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openStudFormMenuitemActionPerformed(evt);
            }
        });
        mainMenu.add(openStudFormMenuitem);

        openLectFormMenuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        openLectFormMenuitem.setText("Преподователи");
        openLectFormMenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openLectFormMenuitemActionPerformed(evt);
            }
        });
        mainMenu.add(openLectFormMenuitem);

        settingsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        settingsMenuItem.setMnemonic('a');
        settingsMenuItem.setText("Настройки");
        settingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsMenuItemActionPerformed(evt);
            }
        });
        mainMenu.add(settingsMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Выход");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        mainMenu.add(exitMenuItem);

        menuBar.add(mainMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Помощь");

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("О программе");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        formWindowClosing(null);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // реализуем диалог подтверждения выхода из программы
        int dialogResult = JOptionPane.showConfirmDialog (null, "Выйти из программы?","Выход", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        aboutDlg.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        
        if(isConnSucess()){
            // подключение успешно
            System.out.println("Успешное подключение к бд");
        } else {
            settDialog.setVisible(true);
        }
        
    }//GEN-LAST:event_formFocusGained

    private void settingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsMenuItemActionPerformed
        settDialog.setVisible(true);
    }//GEN-LAST:event_settingsMenuItemActionPerformed

    private void openStudFormMenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openStudFormMenuitemActionPerformed
        studForm.setVisible(true);
    }//GEN-LAST:event_openStudFormMenuitemActionPerformed

    private void openLectFormMenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openLectFormMenuitemActionPerformed
       lectForm.setVisible(true);
    }//GEN-LAST:event_openLectFormMenuitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //Config.load("config.json");
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu mainMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openLectFormMenuitem;
    private javax.swing.JMenuItem openStudFormMenuitem;
    private javax.swing.JMenuItem settingsMenuItem;
    // End of variables declaration//GEN-END:variables

    private boolean isConnSucess() {
        
        Config.load("config.json");
        String DB_USER = Config.getInstance().DB_USER;
        String DB_PASSWORD = Config.getInstance().DB_PASSWORD;
        String DB_CONN_STRING = Config.getInstance().DB_CONN_STRING;
        
        try {
                    conn = DriverManager.getConnection(DB_CONN_STRING, DB_USER, DB_PASSWORD);
                    this.em = this.emf.createEntityManager();
                    System.out.println("Connected");
                    return true;
                } catch (SQLException e){
                    System.err.println(e.toString());
                    return false;
                }        
    }

}
